config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match "lock/login", to: "lock#login", as: "lock_login", via: :get
  match "lock/refused", to: "lock#refused", as: "unlock_refused", via: :get
  match "lock/unlock", to: "lock#unlock", as: "unlock", via: :post
end

app/controllers/lock_application_controller.rb
# frozen_string_literal: true

module LockApplicationController
  module ClassMethods
    def lock(opts = {})
      before_filter { |c| c.lock_filter opts[:actions] }
    end
  end

  module InstanceMethods
    def lock_filter(actions = nil)
      redirect_to unlock_refused_url if locked_action?(actions) && (session[:lock_opened] != true)
      # otherwise proceed to where ya going
    end

    def locked_action?(actions)
      return false if controller_name == "lock"

      actions.blank? or actions.include?(controller_name.to_s) or actions.include?("#{controller_name}##{action_name}")
    end
  end
end

app/controllers/lock_controller.rb
# frozen_string_literal: true

class LockController < ApplicationController
  def unlock
    if Lock.passwords_match?(params[:password])
      session[:lock_opened] = true
    else
      redirect_to action: :login
    end
  end
end

app/views/lock/login.html.erb
<div class="lock-login" id="lock-login-form">
  <%= form_tag unlock_url do %>
    <%=password_field_tag "password" %>
    <%=submit_tag "Unlock"%>
  <% end %>
</div>

app/views/lock/refused.html.erb
This page is locked.

app/views/lock/unlock.html.erb
Unlocked!
<br/>
<%=link_to "Go to home page", "/" %>